[package]
name = "tortureOS"
version = "0.1.0"
edition = "2024"
authors = ["Darius Bostan <dariusbostan@romus.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"

[[bin]]
name = "tortureOS"
test = false
bench = false
